### ISSUE TITLE
SmartCity LL - page 3

### ISSUE THREAD

**Issue by davidncsco** [CiscoDevNet/clus-train-learning-labs#1]
On page 3, step 5, should read
     Under the downstream label, click on mqtt. Right-click on cisco mqtt, then select Edit Server to see the configuration of the MQTT DSLink.
The next sentence is a little bit confusing: “Note that there are two….” Since there is no such menu as downstream->sys->link. ‘sys’ is on the same menu level as ‘downstream’. That sentence should just be removed.

**Comment by paulzim** [comment]
Fixed
